# -*- coding: utf-8 -*-
"""IK Assignment for 23Aug class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XejwNUE5KSx6Fs4oIQeSVa-Ov4bKMaOA

This cell contains `pip install` commands for various libraries related to LangChain, embeddings, vector stores, web scraping, and Gradio. These commands are used to install necessary packages in the Colab environment.
"""

# !pip install langchain_community
# !pip install langchain chromadb
# !pip install langchain_google_genai
# !pip install langchainhub
# !pip install langchain-openai
# !pip install langchain
# !pip install beautifulsoup4
# !pip install faiss-cpu
# !pip install tavily-python
# !pip gradio_client==0.2.10
# !pip install gradio==3.38.0
# !pip install langchain_chroma

"""This cell imports necessary Python libraries and modules:
- `requests` for making HTTP requests.
- `re` for regular expressions to clean text.
- `BeautifulSoup` from `bs4` for parsing HTML content.
- `urljoin`, `urlparse`, and `urldefrag` from `urllib.parse` for handling URLs.
"""

#from collections import deque
import requests
import re
from bs4 import BeautifulSoup, Comment
from urllib.parse import urljoin, urlparse, urldefrag

"""This cell defines several constants used for web scraping:
- `START_URL`: The initial URL to start the crawling process.
- `BASE_DOMAIN`: The base domain to constrain the crawling.
- `PATH_PREFIX`: A path prefix to limit the crawl to a specific subpath.
- `TIMEOUT`: The timeout in seconds for HTTP requests.
- `REQUEST_DELAY_SEC`: A delay between requests to avoid overwhelming the server.
- `HEADERS`: HTTP headers to mimic a browser request.
- `MAX_PAGES`: The maximum number of pages to crawl.
"""

START_URL = "https://docs.snowflake.com/en/guides"
BASE_DOMAIN = "docs.snowflake.com"
PATH_PREFIX = "/en/guides"  # limit crawl to this subpath
TIMEOUT = 15
REQUEST_DELAY_SEC = 0.5
HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; SimpleBFSBot/1.0; +https://example.local)"
}
MAX_PAGES = 200

"""This cell makes an HTTP GET request to the `START_URL` using the defined headers and timeout, and stores the response in the `resp` variable."""

resp = requests.get(START_URL, headers=HEADERS, timeout=TIMEOUT) #import requests

"""This cell displays the `resp` object, which represents the HTTP response from the `START_URL`. A `<Response [200]>` output indicates a successful request."""

resp

"""This cell retrieves the 'Content-Type' header from the HTTP response and stores it in the `ctype` variable. This is used to check if the content is HTML before parsing."""

ctype = resp.headers.get("Content-Type", "")

"""This cell displays the value of the `ctype` variable to check if response is valid HTML"""

ctype

"""This cell uses BeautifulSoup to parse the HTML content from the `resp.text` and creates a BeautifulSoup object named `soup`."""

soup = BeautifulSoup(resp.text, "html.parser")

"""This cell iterates through a list of HTML tags (script, style, noscript, etc.) and removes them from the parsed HTML (`soup`) to clean the content."""

for tag in soup(["script", "style", "noscript", "template", "svg", "canvas", "iframe", "picture", "source"]):
        tag.decompose()

"""This cell iterates through another list of HTML tags (header, footer, nav, aside) and removes them from the parsed HTML (`soup`)."""

for tag in soup(["header", "footer", "nav", "aside"]):
        tag.decompose()

"""This cell finds all HTML comments in the parsed HTML (`soup`) and extracts them."""

for c in soup.find_all(string=lambda text: isinstance(text, Comment)):
        c.extract()

"""This cell extracts the text content from the cleaned HTML (`soup`), using newline characters as separators and stripping leading/trailing whitespace. The result is stored in the `text` variable."""

text = soup.get_text(separator="\n", strip=True)

"""This cell displays the extracted and cleaned text content of the initial page."""

text

"""This cell uses a regular expression to replace two or more consecutive newline characters with a single newline character in the extracted text, further cleaning the content."""

text = re.sub(r"\n{2,}", "\n", text)

"""This cell displays the text after removing excessive newlines."""

text

"""This cell initializes an empty list called `all_texts` which will be used to store the extracted text content from all crawled pages."""

all_texts = []

"""This cell appends the text extracted from the initial page to the `all_texts` list."""

all_texts.append(text)

"""This cell extracts all URLs from the `href` attributes of `<a>` tags in the parsed HTML (`soup`). It constructs absolute URLs, removes fragments, and adds unique URLs to the `all_urls` list. Finally, it prints the list of extracted URLs."""

all_urls = []
for a in soup.find_all("a", href=True):
  abs_url = urljoin("https://docs.snowflake.com/en/guides", a["href"])
  #print(abs_url)
  abs_url, _ = urldefrag(abs_url)
  new_url = abs_url
  if new_url not in all_urls:
    all_urls.append(new_url)
print(all_urls)

"""This cell displays the number of unique URLs found on the initial page."""

len(all_urls)

"""This cell iterates through the `all_urls` list, visits each URL, checks if the content type is HTML, and if so, extracts and cleans the text content similar to the initial page. The extracted text from each valid HTML page is appended to the `all_texts` list."""

for url in all_urls:
  resp = requests.get(url, headers=HEADERS, timeout=TIMEOUT)
  ctype = resp.headers.get("Content-Type", "")
  if not ("text/html" in ctype.lower() or "application/xhtml+xml" in ctype.lower()):
    continue
  else:
    #print(url)
    soup = BeautifulSoup(resp.text, "html.parser")
    for tag in soup(["script", "style", "noscript", "template", "svg", "canvas", "iframe", "picture", "source"]):
        tag.decompose()
    for tag in soup(["header", "footer", "nav", "aside"]):
        tag.decompose()
    for c in soup.find_all(string=lambda text: isinstance(text, Comment)):
        c.extract()
    text = soup.get_text(separator="\n", strip=True)
    text = re.sub(r"\n{2,}", "\n", text)
    all_texts.append(text)
    #print(text)

"""This cell displays the total number of text documents collected from the initial page and all the linked pages that were crawled to validate if all links were crawled."""

len(all_texts)

"""This cell displays the text content of the third document in the `all_texts` list (index 2)."""

all_texts[2]

"""This cell imports the `SentenceTransformer` class from the `sentence_transformers` library, which is used for creating sentence embeddings."""

from sentence_transformers import SentenceTransformer

"""This cell attempts to load a pre-trained Sentence Transformer model named "all-MiniLM-L6-v2". The output shows the download progress and some warnings related to Hugging Face Hub authentication, but the model is successfully loaded for public models."""

model = SentenceTransformer("all-MiniLM-L6-v2")

"""This cell imports the `SentenceTransformerEmbeddings` class from `langchain_community.embeddings`, which is a LangChain wrapper for Sentence Transformer models to generate embeddings."""

from langchain_community.embeddings import SentenceTransformerEmbeddings

"""This cell initializes a `SentenceTransformerEmbeddings` object using the specified model name. The output includes a deprecation warning, suggesting a newer package for Hugging Face embeddings."""

model_name = "sentence-transformers/all-MiniLM-L6-v2" # Example model
embeddings = SentenceTransformerEmbeddings(model_name=model_name)

"""This cell imports the `FAISS` vector store from `langchain_community.vectorstores` and `RecursiveCharacterTextSplitter` from `langchain_text_splitters`. It then initializes a `RecursiveCharacterTextSplitter` with specified separators, chunk size, and chunk overlap for breaking down text into smaller pieces (chunks)."""

from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(separators= ["\n\n", "\n", " ", ""],chunk_size=1000, chunk_overlap=200) # paragraphs, lines, words, characters, chunk_size=100, chunk_overlap=50

"""This cell uses the initialized `text_splitter` to split the collected text documents (`all_texts`) into smaller chunks, creating a list of `Document` objects."""

documents = text_splitter.create_documents(all_texts)

"""This cell creates a FAISS vector store from the split text documents (`documents`) and their corresponding embeddings generated by the `embeddings` model. This allows for efficient similarity search."""

vector = FAISS.from_documents(documents, embeddings)

"""This cell displays the created FAISS vector store object."""

vector

"""This cell imports the `ChatPromptTemplate` class from `langchain.prompts`, used for creating chat-based prompt templates."""

from langchain.prompts import ChatPromptTemplate

"""This cell imports the `StrOutputParser` from `langchain_core.output_parsers`, which is used to parse the output of a language model as a simple string."""

from langchain_core.output_parsers import StrOutputParser

"""This cell initializes a `StrOutputParser` object."""

output_parser = StrOutputParser()

"""This section sets up a chat prompt template using `ChatPromptTemplate.from_messages`. This template defines the structure of the messages sent to the language model, including a system message to guide the assistant's behavior and human/AI message examples to provide context and demonstrate the desired conversational style. The `{user_input}` placeholder indicates where the user's question will be inserted."""

template = ChatPromptTemplate.from_messages(
    [("system", "You are an assistant for question-answering tasks. Use the provided pieces of retrieved context to answer the question. If you don't know the answer, say that you don't know. Always provide the detailed answer.\n\n"),
    ("human", "Hello, What is Snowflake warehouse used for?"),
    ("ai", "Warehouses are required for queries, as well as all DML operations, including loading data into tables."),
    ("human", "{input}")])

"""This cell imports the `ChatGoogleGenerativeAI` class from `langchain_google_genai`, which allows using Google's Generative AI models within LangChain."""

from langchain_google_genai import ChatGoogleGenerativeAI

"""This cell retrieves the Google API key from Colab's user data, initializes a `ChatGoogleGenerativeAI` model with a specified model name and temperature, and stores it in the `llm` variable."""

from google.colab import userdata
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2, google_api_key=GOOGLE_API_KEY)

"""This cell imports functions `create_retrieval_chain` and `create_stuff_documents_chain` from `langchain.chains` and `langchain.chains.combine_documents` respectively. These are used to build chains for retrieval-based question answering."""

from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain

"""testing prompte formation"""

prompt = template.invoke({"input": "What are the sizes of warehouse Snowflake support?"})

"""Printing promt to validate its structure"""

prompt.messages

"""This cell creates a retriever object from the FAISS vector store, which will be used to search for relevant documents based on a query."""

retriever = vector.as_retriever()

"""This cell creates two chains:
- `document_chain`: Combines the language model (`llm`) with the defined prompt template to answer questions based on provided documents.
- `rag_chain`: Combines the retriever and the question-answer chain to perform retrieval-augmented generation (RAG). It retrieves relevant documents first and then uses the language model to answer the question based on those documents.
"""

document_chain = template | llm
rag_chain = create_retrieval_chain(retriever, document_chain)

"""This cell will invoked the `rag_chain` with a question about Snowflake warehouse sizes."""

response = rag_chain.invoke({"input": "What are the sizes of warehouse Snowflake support?"})

"""This cell will print the answer from the previous `rag_chain` invocation."""

print(response["answer"])

"""Testing few more examples"""

response = rag_chain.invoke({"input": "Where are Larger warehouses available?"})

print(response["answer"])

response = rag_chain.invoke({"input": "What is Streamlit?"})

print(response["answer"])

response = rag_chain.invoke({"input": "How to load data into Snowflake?"})

print(response["answer"])

"""This cell imports the `ConversationBufferMemory` class from `langchain.memory`, which is used to store and manage the conversation history."""

from langchain.memory import ConversationBufferMemory

"""This cell initializes a `ConversationBufferMemory` object with a specified memory key and set to return messages. The output includes a deprecation warning about the class."""

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

"""This cell imports necessary classes for creating agents and tools in LangChain: `AgentExecutor`, `create_tool_calling_agent`, `initialize_agent`, `AgentType` from `langchain.agents`, and `tool` from `langchain_core.tools`."""

from langchain.agents import AgentExecutor, create_tool_calling_agent, initialize_agent, AgentType
from langchain_core.tools import tool

"""This cell defines a custom tool called `retriever_tool` using the `@tool` decorator. This tool takes a query as input, invokes the `rag_chain` to get an answer from the documentation, and returns the answer."""

@tool
def retriever_tool(query: str) -> str:
  """Searches and returns answer to the query from the provided documentation."""
  response = rag_chain.invoke({"input": query})
  return response["answer"]

"""This cell imports the `TavilySearchResults` tool from `langchain_community.tools.tavily_search`, which allows performing searches using the Tavily API."""

from langchain_community.tools.tavily_search import TavilySearchResults

"""This cell retrieves the Tavily API key from Colab's user data and initializes a `TavilySearchResults` tool. The output includes a deprecation warning about the class."""

from google.colab import userdata
TAVILY_API_KEY = userdata.get('TAVILY_API_KEY')
search = TavilySearchResults(tavily_api_key=TAVILY_API_KEY)

"""This cell creates a list of tools that the agent can use, including the custom `retriever_tool` and the `search` tool."""

tools = [retriever_tool,search]

""" This cell initializes a LangChain agent using the defined tools, language model (`llm`), memory, and agent type (`CONVERSATIONAL_REACT_DESCRIPTION`). The `verbose=True` setting enables detailed logging of the agent's actions. The output includes a deprecation warning about using `initialize_agent`."""

agent = initialize_agent(
    tools=tools,
    llm = llm,
    memory=memory,
    agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True
)

"""This cell defines a function `handle_user_message` that takes user input, passes it to the initialized agent (`agent`), runs the agent, and returns the agent's response."""

def handle_user_message(user_input):
    response = agent.run(user_input)
    return response

"""Compare Rag chain response vs agent response"""

response = rag_chain.invoke({"input": "What is ChatGPT?"})

print(response["answer"])

handle_user_message("What is ChatGPT?")

handle_user_message("How to bulk load data from AWS S3?")

handle_user_message("Which is the Snowflake latest feature? What does it do? ")

handle_user_message("Which is the Snowflake latest feature? Select 1 feature and tell me what does it do? ")

memory.clear()

handle_user_message("Which is the Snowflake latest feature? Select 1 feature and tell me what does it do? ")

handle_user_message("Which is the Snowflake latest feature?  Is it avialabile in our context? ")

handle_user_message("What are the sizes of warehouse Snowflake support?")

"""Validate Memory feature"""

handle_user_message("What question did i ask you before?")

"""This cell imports the `gradio` library, which is used to create a web-based user interface for the chatbot."""

import gradio as gr

"""This cell defines a function `predict` that takes a user message and chat history as input, and uses the `handle_user_message` function (defined previously) to get a response from the agent."""

def predict(message, _):
 result = handle_user_message(message)
 return result

"""This code block sets up a Gradio chat interface.
- It uses the `predict` function to handle user input and generate responses.
- It configures the appearance of the chatbot and textbox.
- It sets a title and theme for the interface.
- It provides example questions for the user to start with.
- Finally, it launches the Gradio application, making it accessible via a public URL.
"""

gr.ChatInterface(
    predict,
    chatbot= gr.Chatbot(height=300),
    textbox= gr.Textbox(placeholder = "Hi I am your virtual assistant, how can I help you today?", container=False, scale=7),
    title = "SnowflakeBot",
    theme = "soft",
    examples = ["What is Snowflake?", "What are warehouses in Snowflake?"],
    #undo_btn = "Delete Previous",
    #clear_btn = "Clear"
).launch(share=True)

goog